on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.1
    - uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '11'
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: bundle-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: bundle
    - run: bundle install --jobs 4 --retry 3 --deployment
    - run: bundle exec rake
